### PR TITLE
Add dandi_etag digest type to schema

### PR DESCRIPTION
**Pull request by jwodder**
See [here](https://github.com/dandi/dandi-cli/pull/479#discussion_r598897361) and related conversation.

Note that I changed the name of the enum from `dandi-etag` to `dandi_etag` so that it would be a valid Python identifier.

### CODE REVIEW

**Comment by yarikoptic** [comment]
> Note that I changed the name of the enum from `dandi-etag` to `dandi_etag` so that it would be a valid Python identifier.

does it need to be a proper Python identifier?

**Comment by jwodder** [comment]
@yarikoptic The name gets used as the name of the enum instance, so if we ever want to use the enum as an enum, yes, it needs to be a valid identifier.

**Comment by yarikoptic** [comment]
I see that we also have e.g. `dandi:CCBYNC40` (which imho should better be `dandi:CC-BY-NC-40` or alike) and wonder if we haven't already catered to some pydantic/python inflicted limitation a bit too much.

I think it matters only for `klass` name generation, so may be we should just `klass = klass.replace('-', '_')` and thus allow `@id` to contain `-` and thus remain more readable etc.  Or there is more to it, @satra?

I see also in that code of `create_enum` that we use
```python
            if key in items:
                key = item["@id"].replace(":", "_")
```
but I do not think we use this one anywhere, thus could be removed?

If we remove, then I think we could even have 1-to-1 mapping from Enum klass name back into original `@id` value if so desired, so we keep `_` in Python classes and `-` in json schema values etc.  I think it might be useful in the long run.

**Comment by yarikoptic** [comment]
@jwodder if you do not see immediate danger in replacing `-` with `_` for Enum `klass` name minting, to not keep upload RFing #478 blocked, let's introduce that mapping, while keeping it `dandi-etag` so it is aligned with what API expects ATM.

**Comment by jwodder** [comment]
@yarikoptic Done.

**Comment by satra** [comment]
feel free to go improving identifier names. i wouldn't go crazy but anything allowed in a URL is fine.

**Comment by yarikoptic** [comment]
ok, let's proceed with this

**Pull request merged**
