### PR TITLE
Changing `docker-compose` to docker `docker compose` subcommand

### PR DESCRIPTION
**Pull request by TheChymera**
Fixes https://github.com/dandi/dandi-cli/issues/1042

### CODE REVIEW

**Comment by yarikoptic** [comment]
Dear @TheChymera please adjust title of the PR to be "self-sufficient" as it becomes also an entry in the ChangeLog file.  `using subcommand` by itself is not descriptive enough

**Comment by yarikoptic** [comment]
It seems to fail now with
```
2022-07-05T01:57:24.4354023Z Container dandiarchive-docker-rabbitmq-1  Started
2022-07-05T01:57:25.4442331Z Container dandiarchive-docker-minio-1  Started
2022-07-05T01:57:35.3491280Z 
2022-07-05T01:57:35.3492387Z You have 64 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): account, admin, api, auth, authtoken, contenttypes, guardian, oauth2_provider, sessions, sites, socialaccount.
2022-07-05T01:57:35.3493417Z Run 'python manage.py migrate' to apply them.
2022-07-05T01:57:35.3520866Z Traceback (most recent call last):
2022-07-05T01:57:35.3534748Z   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
2022-07-05T01:57:35.3574066Z     return self.cursor.execute(sql, params)
2022-07-05T01:57:35.3574553Z psycopg2.errors.UndefinedTable: relation "auth_user" does not exist
2022-07-05T01:57:35.3575055Z LINE 1: ...user"."is_active", "auth_user"."date_joined" FROM "auth_user...
2022-07-05T01:57:35.3575456Z                                                              ^
2022-07-05T01:57:35.3575657Z 
2022-07-05T01:57:35.3575678Z 
2022-07-05T01:57:35.3575890Z The above exception was the direct cause of the following exception:
2022-07-05T01:57:35.3576172Z 
2022-07-05T01:57:35.3576328Z Traceback (most recent call last):
2022-07-05T01:57:35.3576795Z   File "/opt/django/./manage.py", line 20, in <module>
2022-07-05T01:57:35.3578049Z     main()
2022-07-05T01:57:35.3579050Z   File "/opt/django/./manage.py", line 16, in main
2022-07-05T01:57:35.3579431Z     execute_from_command_line(sys.argv)
2022-07-05T01:57:35.3580264Z   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
2022-07-05T01:57:35.3581162Z     utility.execute()
2022-07-05T01:57:35.3581829Z   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
2022-07-05T01:57:35.3582331Z     self.fetch_command(subcommand).run_from_argv(self.argv)
2022-07-05T01:57:35.3583018Z   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 414, in run_from_argv
2022-07-05T01:57:35.3583455Z     self.execute(*args, **cmd_options)
2022-07-05T01:57:35.3584164Z   File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 87, in execute
2022-07-05T01:57:35.3584661Z     return super().execute(*args, **options)
2022-07-05T01:57:35.3585293Z   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 460, in execute
2022-07-05T01:57:35.3585743Z     output = self.handle(*args, **options)
2022-07-05T01:57:35.3586477Z   File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 211, in handle
2022-07-05T01:57:35.3586947Z     error_msg = self._validate_username(
2022-07-05T01:57:35.3587692Z   File "/usr/local/lib/python3.9/site-packages/composed_configuration/_allauth_support/createsuperuser.py", line 26, in _validate_username
2022-07-05T01:57:35.3588534Z     return super()._validate_username(username, verbose_field_name, database)
2022-07-05T01:57:35.3589352Z   File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 284, in _validate_username
2022-07-05T01:57:35.3589938Z     self.UserModel._default_manager.db_manager(database).get_by_natural_key(
2022-07-05T01:57:35.3590658Z   File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/base_user.py", line 46, in get_by_natural_key
2022-07-05T01:57:35.3591158Z     return self.get(**{self.model.USERNAME_FIELD: username})
2022-07-05T01:57:35.3591817Z   File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
2022-07-05T01:57:35.3592307Z     return getattr(self.get_queryset(), name)(*args, **kwargs)
2022-07-05T01:57:35.3592956Z   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 492, in get
2022-07-05T01:57:35.3593357Z     num = len(clone)
2022-07-05T01:57:35.3593928Z   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 302, in __len__
2022-07-05T01:57:35.3594333Z     self._fetch_all()
2022-07-05T01:57:35.3595012Z   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1507, in _fetch_all
2022-07-05T01:57:35.3595492Z     self._result_cache = list(self._iterable_class(self))
2022-07-05T01:57:35.3596122Z   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 57, in __iter__
2022-07-05T01:57:35.3596555Z     results = compiler.execute_sql(
2022-07-05T01:57:35.3597203Z   File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1361, in execute_sql
2022-07-05T01:57:35.3597629Z     cursor.execute(sql, params)
2022-07-05T01:57:35.3598235Z   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 103, in execute
2022-07-05T01:57:35.3598672Z     return super().execute(sql, params)
2022-07-05T01:57:35.3599286Z   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
2022-07-05T01:57:35.3599717Z     return self._execute_with_wrappers(
2022-07-05T01:57:35.3600382Z   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
2022-07-05T01:57:35.3600841Z     return executor(sql, params, many, context)
2022-07-05T01:57:35.3601464Z   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
2022-07-05T01:57:35.3601918Z     return self.cursor.execute(sql, params)
2022-07-05T01:57:35.3602514Z   File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
2022-07-05T01:57:35.3603022Z     raise dj_exc_value.with_traceback(traceback) from exc_value
2022-07-05T01:57:35.3603857Z   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
2022-07-05T01:57:35.3604297Z     return self.cursor.execute(sql, params)
2022-07-05T01:57:35.3604747Z django.db.utils.ProgrammingError: relation "auth_user" does not exist
2022-07-05T01:57:35.3605224Z LINE 1: ...user"."is_active", "auth_user"."date_joined" FROM "auth_user...
2022-07-05T01:57:35.3605619Z                                                              ^
2022-07-05T01:57:35.3605821Z 
2022-07-05T01:57:35.9618665Z ERROR
2022-07-05T01:57:36.0201990Z dandi/tests/test_dandiapi.py::test_publish_and_manipulate ERROR
2022-07-05T01:57:36.0782037Z dandi/tests/test_dandiapi.py::test_get_asset_metadata ERROR
2022-07-05T01:57:36.1364928Z dandi/tests/test_dandiapi.py::test_large_upload ERROR
2022-07-05T01:57:36.1937398Z dandi/tests/test_dandiapi.py::test_authenticate_bad_key_good_key_input ERROR

```
and thus leading to all those errors you see. @jwodder and @dandi/archive-maintainers - any clues why those migrations are failing now/whenever invoking `docker compose` instead of `docker-compose`?

**Comment by jwodder** [comment]
@yarikoptic I am unable to reproduce this failure locally.  Both `docker-compose` and `docker compose` work for me with the latest dandiarchive image with Docker 20.10.17.

**Comment by yarikoptic** [comment]
pushed adding of reporting on version and what we would see when we do try to run `docker compose` there. It might be that github still has docker version which doesn't know how to deal with `docker compose`.

> Apparently it's now a subcommand and DANDI tests will fail with newer docker ...

how new it should be (ie. in what docker version was introduced allowing for `docker compose` and either it requires specific minimal version of docker-compose for that if those are two separate projects, I don't know)?
I guess (since both forms work for @jwodder) there some deprecation cycle when both are still supported. So I wonder if we should delay "until no longer"?
We might not be able to "just switch" like you suggested here for a while as long as older versions are still in use. Fixture might need to do `docker -v` checking on which form it should use.

**Comment by TheChymera** [comment]
Today I learned that the docker source code is all over the place and absolutely intransparent... Couldn't find the actual commit or changelog, but this is the roadmap issue where they discussed the change: https://github.com/docker/roadmap/issues/15

It looks like it was rolled out about a year ago. I suggest we leave this open and revisit in a few months.

**Comment by yarikoptic** [comment]
Let's reopen whenever we get to it

**Pull request closed without merging**
