### PR TITLE
Update for dandischema 0.8.0

### LINKED ISSUE #1249: dandi version error in staging
```pytb
def test_automatic_dandi_upload(self):
>       automatic_dandi_upload(dandiset_id="200560", nwb_folder_path=self.nwb_folder_path, staging=True)

tests/test_minimal/test_tools/test_dandi_transfer_tools.py:45: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/neuroconv/tools/data_transfers.py:[36](https://github.com/catalystneuro/neuroconv/actions/runs/4378541440/jobs/7663420144#step:9:37)4: in automatic_dandi_upload
    dandi_upload(paths=[str(x) for x in organized_nwbfiles], dandi_instance=dandi_instance)
/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/dandi/upload.py:70: in upload
    client.check_schema_version()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <dandi.dandiapi.DandiAPIClient object at 0x7f3f9cb34910>
schema_version = '0.6.3'

    def check_schema_version(self, schema_version: Optional[str] = None) -> None:
        """
        Confirms that the server is using the same version of the Dandi schema
        as the client.  If it is not, a `SchemaVersionError` is raised.
    
        :param schema_version: the schema version to confirm that the server
            uses; if not set, the schema version for the installed
            ``dandischema`` library is used
        """
        if schema_version is None:
            schema_version = models.get_schema_version()
        server_info = self.get("/info/")
        server_schema_version = server_info.get("schema_version")
        if not server_schema_version:
            raise RuntimeError(
                "Server did not provide schema_version in /info/;"
                f" returned {server_info!r}"
            )
        if server_schema_version != schema_version:
>           raise SchemaVersionError(
                f"Server requires schema version {server_schema_version};"
                f" client only supports {schema_version}.  You may need to"
                " upgrade dandi and/or dandischema."
            )
E           dandi.exceptions.SchemaVersionError: Server requires schema version 0.6.4; client only supports 0.6.3.  You may need to upgrade dandi and/or dandischema.
```

### PR DESCRIPTION
**Pull request by jwodder**
Blocked by https://github.com/dandi/dandi-archive/issues/1520.

There are still some typing errors that will be resolved once https://github.com/dandi/dandi-schema/pull/163 is merged & released.

Closes #1249

### CODE REVIEW

**Comment by yarikoptic** [comment]
type checking isn't happy.
Also dandi-archive merged https://github.com/dandi/dandi-archive/pull/1524#event-8711479569 now , but not released. If we refresh -- will CI use/test against staging?

**Comment by jwodder** [comment]
@yarikoptic The CI will use a Docker image built from the latest commit to `master` on dandi-archive, so it would effectively be testing against staging.

**Comment by yarikoptic** [comment]
typechecking is still red

**Comment by satra** [comment]
archive released an update setting minimium version to `0.6.4` this needs to be released asap to prevent clients from erroring. see #1249

**Comment by yarikoptic** [comment]
> archive released an update setting minimium version to `0.6.4` this needs to be released asap to prevent clients from erroring. see #1249

it didn't release yet . #1249 I believe is against staging -- see dandiset id there.

**Comment by CodyCBakerPhD** [comment]
> https://github.com/dandi/dandi-cli/issues/1249 I believe is against staging -- see dandiset id there.

It's true, the CI tests upload to staging. Just wanted you to be aware as soon as it happened so same doesn't happen to the main server

**Comment by yarikoptic** [comment]
pushed fix for typing

**Comment by yarikoptic** [comment]
I dislike our too rigid dependency on versions correspondence... we should reconsider.
Meanwhile -- we will merge tomorrow in coordination with the release of the dandi-archive  itself (attn @dandi/dandiarchive @dandi/archive-admin )

**Pull request merged**
