### PR TITLE
Add title to `Field` calls where necessary

### PR DESCRIPTION
**Pull request by AlmightyYakob**
This is something I've noticed for a while now, and figured I'd just add these titles. Almost all of the titles are just the variable name with capitalization and spaces, so I doubt there's much wrong here, but if there is please lmk.

### CODE REVIEW

**Comment by yarikoptic** [comment]
although "explicit better than implicit" I generally prefer to avoid duplication.
I wonder why just not at the level of UI to apply the rule of having `camelCased` to become `Camel Cased` and apply rules to downcase `of`, `to` etc if encountered upon splitting?

**Comment by yarikoptic** [comment]
FWIW, might be better to have that "code" to be actually here within schema conversion tools, so produced .json would already have titles.  That would centralize the code and not offload it upon UIs.

**Comment by satra** [comment]
@AlmightyYakob - i sent some changes on top of yours (feel free to merge that). i was mostly focusing on the non-autogenerated ones. the reason license was misbehaving is that pydantic does not generate titles automatically for fields that have a type that's an enum. (i don't know why). so i fixed titles for all of them.

**Comment by AlmightyYakob** [comment]
> FWIW, might be better to have that "code" to be actually here within schema conversion tools, so produced .json would already have titles. That would centralize the code and not offload it upon UIs.

I agree, as otherwise it's more code that splits the schema used in the UI from the source schema. I realize that title formatting is a pretty small change, but JSON Schema is designed to be able to specify this information, without intervention from whatever is displaying it.

**Comment by yarikoptic** [comment]
> > FWIW, might be better to have that "code" to be actually here within schema conversion tools, so produced .json would already have titles. That would centralize the code and not offload it upon UIs.
> 
> I agree, as otherwise it's more code that splits the schema used in the UI from the source schema. I realize that title formatting is a pretty small change, but JSON Schema is designed to be able to specify this information, without intervention from whatever is displaying it.

ok, filed https://github.com/dandi/dandi-cli/issues/301 so could be done after to not hold this PR hostage

**Comment by jwodder** [comment]
I've submitted a PR on the head repository to fix the failing tests: https://github.com/AlmightyYakob/dandi-cli/pull/3

**Comment by yarikoptic** [comment]
well, don't we need PRs to come from branches in this repository to get access to some secrets? then this PR should be redone from a branch here anyways.  @jwodder , please just submit a new PR from a branch here to supersede this PR. @AlmightyYakob is also part of the team , so he should be able to push directly to that branch if would be needed

**Comment by jwodder** [comment]
@yarikoptic Are you sure superseding this PR is necessary?  The only secret the test workflow relies on is for pushing to Codecov.

**Comment by yarikoptic** [comment]
we can wait for all the dance with merging of a PR for a PR to happen and then ignore codecov, or could just streamline with superseded PR with all the commits desired to bring it to the finish line together.  up to you ;)

**Comment by AlmightyYakob** [comment]
> @AlmightyYakob is also part of the team , so he should be able to push directly to that branch if would be needed

Do I have contributor access on this repo? If so, then in the future I'm happy to deal with branches here directly.

**Comment by yarikoptic** [comment]
> > @AlmightyYakob is also part of the team , so he should be able to push directly to that branch if would be needed
> 
> Do I have contributor access on this repo? If so, then in the future I'm happy to deal with branches here directly.

AFAIK yes, you are part of the dandi-cli team https://github.com/orgs/dandi/teams/dandi-cli/members

**Comment by yarikoptic** [comment]
ok, since @satra did not raise any concerns, I guess it is good to go!

**Pull request merged**
