### PR TITLE
upload(): Only yield first "validating" status to pyout

### PR DESCRIPTION
**Pull request by jwodder**
Completes #405.

### CODE REVIEW

**Comment by yarikoptic** [comment]
I thought it is not needed since we yield at this point: https://github.com/dandi/dandi-cli/blob/master/dandi/upload.py#L258

**Comment by jwodder** [comment]
@yarikoptic That's for client-side validation before upload.  This status is yielded while waiting for server-side validation after upload.

**Comment by yarikoptic** [comment]
d'oh -- right.  We should come up with some different term for the things. Ok, let's proceed then

**Comment by yarikoptic** [comment]
Thank you

**Pull request merged**
