### PR TITLE
Support for `dandi upload README`

### PR DESCRIPTION
**Pull request by TheChymera**
Closes: https://github.com/dandi/dandi-cli/issues/1252

### CODE REVIEW

**Comment by TheChymera** [comment]
@yarikoptic so the use case of `dandi upload /path/to/dandiset-bids/README` (still needs full path pending ) works as of [5047f7f](https://github.com/dandi/dandi-cli/pull/1271/commits/5047f7f5e0006b4103862de47c7d8fe565b1056b).

Sadly if I try to formulate a test for this (see [e97aa99](https://github.com/dandi/dandi-cli/pull/1271/commits/e97aa99a7f7d1c2bce471aba9f944a41ab058834)) it fails with:

```
dandi/files/bids.py:168: in bids_dataset_description
    assert bdd is not None
E   AssertionError
```

The issue seems to be that the `bids_dataset_description_ref` of the `GenericBIDSAsset` is dead.
Inserting a `print(self)` [here](https://github.com/dandi/dandi-cli/blob/eef8443a16f0968891f4ddfca43d663df3f07f2b/dandi/files/bids.py#L167) gives me:

```
GenericBIDSAsset(filepath=PosixPath('/tmp/pytest-of-chymera/pytest-29/dandiset0/README'), dandiset_path=PosixPath('/tmp/pytest-of-chymera/pytest-29/dandiset0'), path='README', bids_dataset_description_ref=<weakref at 0x7f7a742ad3f0; dead>)
```

@jwodder any idea what I could do about it?

**Comment by jwodder** [comment]
@TheChymera

* The problem is that the BIDS assets code assumes that a `BIDSDatasetDescriptionAsset` will always be stored somewhere other than in the weakref of a `BIDSAsset`, which is not the case for the `bidsdd` created by this PR; since the `bidsdd` is never yielded by `find_dandi_files()`, it's soon garbage collected, and the weakrefs in the assets that were yielded end up dead.
* Disregarding the weakref issue, this PR is flawed on multiple levels:
   * It should check all directories between `dandiset_path` and `p` for a `BIDS_DATASET_DESCRIPTION`, not just `p.parent`.
   * It does not handle directories in `paths` that are inside directories containing `BIDS_DATASET_DESCRIPTION`.
   * If `BIDS_DATASET_DESCRIPTION` is not found anywhere beneath a given element of `paths`, the code will end up checking for `BIDS_DATASET_DESCRIPTION` for every file at every level beneath the path.
   
    It would be better to insert above line 108 a search for a `BIDS_DATASET_DESCRIPTION` between `dandiset_path` & `p` and use the result in place of the `None` on line 108.

**Comment by TheChymera** [comment]
@jwodder better? :)

**Comment by jwodder** [comment]
@TheChymera Somewhat, except that now `find_dandi_files()` can yield assets outside of `paths`, which it shouldn't, and which will result in `dandi upload` also uploading `dataset_description.json` even when that's not under the given paths.

**Comment by TheChymera** [comment]
@jwodder any ideas about this? seems however I try it if `dataset_description.json` isn't uploaded the wekref is dead, and it won't validate :(

**Comment by jwodder** [comment]
Closing in favor of #1286.

**Pull request closed without merging**
