### PR TITLE
Don't even test for `cp --reflink` support on Windows

### LINKED ISSUE #1218: on windows dandi organise returns an error
Windows version = 11
Python version = 3.7.13
Dandi version =  0.49.1

```python
In [1]: import subprocess

In [2]: r = subprocess.run(["cp","--help"],
   ...: stdout = subprocess.PIPE,
   ...: stderr = subprocess.STDOUT,
   ...: universal_newlines = True,)
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-2-aca17b0af0aa> in <module>
      2 stdout = subprocess.PIPE,
      3 stderr = subprocess.STDOUT,
----> 4 universal_newlines = True,)

~\anaconda3\lib\subprocess.py in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    486         kwargs['stderr'] = PIPE
    487
--> 488     with Popen(*popenargs, **kwargs) as process:
    489         try:
    490             stdout, stderr = process.communicate(input, timeout=timeout)

~\anaconda3\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors, text)
    798                                 c2pread, c2pwrite,
    799                                 errread, errwrite,
--> 800                                 restore_signals, start_new_session)
    801         except:
    802             # Cleanup if the child failed starting.

~\anaconda3\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
   1205                                          env,
   1206                                          os.fspath(cwd) if cwd is not None else None,
-> 1207                                          startupinfo)
   1208             finally:
   1209                 # Child is launched. Close the parent's copy of those pipe

FileNotFoundError: [WinError 2] The system cannot find the file specified
```

### PR DESCRIPTION
**Pull request by jwodder**
Closes #1218.

### CODE REVIEW

**Comment by yarikoptic** [comment]
eh, tests are failing due to http://www.ontobee.org/ to which URLs like http://purl.obolibrary.org/obo/NCBITaxon_10090-value0 get redirected being down!  I feel that we might need to do something about such level of integration testing sooner than later :-/   @satra  already filed an issue: https://github.com/OntoZoo/ontobee/issues/189 . Let's hope for quick resolution.

But I also see a fail which might be related to this PR and not above: in [test (windows-2019, 3.7, normal)](https://github.com/dandi/dandi-cli/actions/runs/4256202751/jobs/7404773564#logs)

```
FAILED dandi/tests/test_organize.py::test_organize_nwb_test_data[simulate] - AssertionError: assert [] == ['sub-RAT123\\sub-RAT123.nwb']
  Right contains one more item: 'sub-RAT123\\sub-RAT123.nwb'
  Full diff:
  - ['sub-RAT123\\sub-RAT123.nwb']
  + []
FAILED dandi/tests/test_organize.py::test_organize_nwb_test_data[copy] - AssertionError: assert [] == ['sub-RAT123\\sub-RAT123.nwb']
  Right contains one more item: 'sub-RAT123\\sub-RAT123.nwb'
  Full diff:
  - ['sub-RAT123\\sub-RAT123.nwb']
  + []
FAILED dandi/tests/test_organize.py::test_organize_nwb_test_data[hardlink] - AssertionError: assert [] == ['sub-RAT123\\sub-RAT123.nwb']
  Right contains one more item: 'sub-RAT123\\sub-RAT123.nwb'
  Full diff:
  - ['sub-RAT123\\sub-RAT123.nwb']
  + []
FAILED dandi/tests/test_organize.py::test_organize_nwb_test_data[symlink] - AssertionError: assert [] == ['sub-RAT123\\sub-RAT123.nwb']
  Right contains one more item: 'sub-RAT123\\sub-RAT123.nwb'
  Full diff:
  - ['sub-RAT123\\sub-RAT123.nwb']
  + []
FAILED dandi/tests/test_organize.py::test_organize_nwb_test_data[auto] - AssertionError: assert [] == ['sub-RAT123\\sub-RAT123.nwb']
  Right contains one more item: 'sub-RAT123\\sub-RAT123.nwb'
  Full diff:
  - ['sub-RAT123\\sub-RAT123.nwb']
  + []
```
another windows I checked also has this fail, and ubuntu too https://github.com/dandi/dandi-cli/actions/runs/4256202751/jobs/7404774950 ... odd -- I don't see how this PR change could have affected that .  May be somehow that metadata business affecting organize! let's wait for service to come back first

**Comment by yarikoptic** [comment]
please rebase on master - we should be clean (in non-dev) again

**Comment by jwodder** [comment]
@yarikoptic Rebased.

**Comment by yarikoptic** [comment]
It's green, great. Pynwb issue shay was fixed upstream by tireless @rly so we are really green. Merging

**Pull request merged**
