### PR TITLE
ENH: add uploaded_by field which would inform what version of dandi client uploaded it

### PR DESCRIPTION
**Pull request by yarikoptic**
I should have done it before 0.5.0 ;-)

### CODE REVIEW

**Comment by yarikoptic** [comment]
@satra @mgrauer - any objections/recommendations?

**Comment by satra** [comment]
nope

**Comment by yarikoptic** [comment]
failed test runs seems to be due to #111

**Comment by mgrauer** [comment]
seems like it will be helpful for debugging, no objections

**Pull request merged**
