### PR TITLE
Drop claiming support and testing against EOL Python 3.8

### PR DESCRIPTION
**Pull request by asmacdo**
Fixes https://github.com/dandi/dandi-cli/issues/1503

### CODE REVIEW

**Comment by yarikoptic** [comment]
not yet, in a month or so whenever it actually EOLs

**Comment by asmacdo** [comment]
The 3.12 Test breaking is unrelated, its just a flake. 

I bumped the timeout [here](https://github.com/dandi/dandi-cli/pull/1505) fwiw.

**Comment by asmacdo** [comment]
I thought it was EOL on October 14, but its gone as of October 7. https://devguide.python.org/versions/

**Comment by yarikoptic** [comment]
Thank you! I am also going through similar fun activities in other corners

**Pull request merged**
