### PR TITLE
Remove dandi/core/ in favor of copy in dandischema

### PR DESCRIPTION
**Pull request by jwodder**
As instructed [here](https://github.com/dandi/dandischema/pull/100#discussion_r764118777).

### CODE REVIEW

**Comment by yarikoptic** [comment]
Thanks!  Let's hope that nobody used those helpers directly (checked our dandisets tools -- nope), otherwise (and ideally) we should have provided some deprecation cycle with all the warnings + shim imports.

**Comment by yarikoptic** [comment]
BTW, how do you look @jwodder  at just making `dandi-cli` finally to start following semver closer and us to mark this one as `major`? ;)

**Comment by jwodder** [comment]
@yarikoptic Marking a PR as "major" would mean that the next release would be v1.0.0, which we shouldn't do at this point.  Note that [the semver spec](https://semver.org/#spec-item-4) permits breaking changes at any point during 0.x.y development.

**Comment by yarikoptic** [comment]
> v1.0.0, which we shouldn't do at this point

why?

> Note that the semver spec permits breaking changes at any point during 0.x.y development.

I am aware of that.  So, yes -- it just "disclaims" responsibility for breaking API.  If we release 1.0.0, we indeed might plan better for the next "major" release, or just progress through a number of them until some (e.g. 10.0.0) could be declared to be a "stable" one and we only then start paying more attention to not breaking API.

**Comment by jwodder** [comment]
@yarikoptic I'd say we shouldn't release v1 until at least the Python API rewrite is done, possibly including the rewrite of `download()` etc. to make it return pyout dicts.

**Pull request merged**
