### PR TITLE
Display `dandi validate` errors using logger

### LINKED ISSUE #458: incomplete log file created by validation
the log files created by `dandi validate` do not contain any information about errors.

### PR DESCRIPTION
**Pull request by jwodder**
Closes #458.

### CODE REVIEW

**Comment by yarikoptic** [comment]
thank you @jwodder , let it be like this for now.  validation is yet to be RFed later on (#431 etc), so we will tune later

**Comment by djarecka** [comment]
thanks for addressing my issue. Unfortunately, the output is now much less readable IMO

before:
Screen Shot 2021-03-11 at 8 54 54 AM
after:
Screen Shot 2021-03-11 at 8 55 35 AM

Let me know if you want me to open a separate issue.

**Comment by jwodder** [comment]
@yarikoptic What exactly should the output look like?

**Comment by yarikoptic** [comment]
IMHO it is ok (although not colored) -- the only thing is that `%s: ok` I have missed - somewhere path was not provided.
Or @djarecka what readability aspect you have in mind?

**Comment by jwodder** [comment]
@yarikoptic I fixed the "%s: ok" thing in #462.

**Comment by djarecka** [comment]
@yarikoptic - it doesn't provide info about files that are not failing, and yes the color also helps

**Comment by djarecka** [comment]
@jwodder - thanks, your PR helps! The color is gone, but I guess, we can live with this.

**Comment by yarikoptic** [comment]
yes, let's live without colors for now.  Later we will RF for more consistent handling of outputs etc and I hope that is when colors would return ;-)

**Pull request merged**
