### PR TITLE
Use oldest file when race condition causes multiple files per item

### LINKED ISSUE #264: race between upload and download leads to a crash
We (ab)use girder so that we expect only 1 file per item.  But also to ensure that we are not leaving user without any file during download if a new version is being uploaded, or to end up without an item/file if upload fails,  we first upload new and then delete old file IIRC (yet to check code).  but that could lead to: 

When uploading a new version of a file 
<details>
<summary>details from the cron job</summary> 

```shell
2020-11-05T12:12:03-0500 [INFO    ] backups2datalad.py Syncing Dandiset 000003                                                                                                                                                                                                                                                                                                                                     
2020-11-05T12:12:04-0500 [INFO    ] dandi Traversing remote dandisets (000003) recursively                                                                                                                                                                                                                                                                                                                         
2020-11-05T12:12:04-0500 [INFO    ] backups2datalad.py Updating metadata file                                                                                                                                                                                                                                                                                                                                      
2020-11-05T12:12:04-0500 [WARNING ] dandi Ran into an empty item: {'_id': '5fa42f0b271e91aad754e4b5', '_modelType': 'item', 'baseParentId': '5e59bb0af19e820ab6ea6c62', 'baseParentType': 'collection', 'created': '2020-11-05T16:57:47.668000+00:00', 'creatorId': '5ee6c160155e470d51c94881', 'description': '', 'folderId': '5e73fad0368d3c79a8006c12', 'meta': {}, 'name':                                     
'sub-YutaMouse20_ses-YutaMouse20-140321_behavior+ecephys.nwb', 'size': 0, 'updated': '2020-11-05T16:57:47.668000+00:00'}                                                                                                                                                                                                                                                                                           
2020-11-05T12:12:04-0500 [WARNING ] dandi Ran into an empty item: {'_id': '5fa42eef271e91aad754e4b1', '_modelType': 'item', 'baseParentId': '5e59bb0af19e820ab6ea6c62', 'baseParentType': 'collection', 'created': '2020-11-05T16:57:19.391000+00:00', 'creatorId': '5ee6c160155e470d51c94881', 'description': '', 'folderId': '5e73fad0368d3c79a8006c12', 'meta': {}, 'name':                                     
'sub-YutaMouse20_ses-YutaMouse20-140324_behavior+ecephys.nwb', 'size': 0, 'updated': '2020-11-05T16:57:19.391000+00:00'}                                                                                                                                                                                                                                                                                           
2020-11-05T12:12:04-0500 [WARNING ] dandi Ran into an empty item: {'_id': '5fa42f1d271e91aad754e4ba', '_modelType': 'item', 'baseParentId': '5e59bb0af19e820ab6ea6c62', 'baseParentType': 'collection', 'created': '2020-11-05T16:58:05.895000+00:00', 'creatorId': '5ee6c160155e470d51c94881', 'description': '', 'folderId': '5e73fad0368d3c79a8006c12', 'meta': {}, 'name':                                     
'sub-YutaMouse20_ses-YutaMouse20-140325_behavior+ecephys.nwb', 'size': 0, 'updated': '2020-11-05T16:58:05.895000+00:00'}                                                                                                                                                                                                                                                                                           
2020-11-05T12:12:04-0500 [WARNING ] dandi Ran into an empty item: {'_id': '5fa42f00271e91aad754e4b3', '_modelType': 'item', 'baseParentId': '5e59bb0af19e820ab6ea6c62', 'baseParentType': 'collection', 'created': '2020-11-05T16:57:35.985000+00:00', 'creatorId': '5ee6c160155e470d51c94881', 'description': '', 'folderId': '5e73fad0368d3c79a8006c12', 'meta': {}, 'name':                                     
'sub-YutaMouse20_ses-YutaMouse20-140327_behavior+ecephys.nwb', 'size': 0, 'updated': '2020-11-05T16:57:35.985000+00:00'}                                                                                                                                                                                                                                                                                           
2020-11-05T12:12:05-0500 [WARNING ] dandi Ran into an empty item: {'_id': '5fa42f10271e91aad754e4b7', '_modelType': 'item', 'baseParentId': '5e59bb0af19e820ab6ea6c62', 'baseParentType': 'collection', 'created': '2020-11-05T16:57:52.589000+00:00', 'creatorId': '5ee6c160155e470d51c94881', 'description': '', 'folderId': '5e73fad0368d3c79a8006c12', 'meta': {}, 'name':                                     
'sub-YutaMouse20_ses-YutaMouse20-140328_behavior+ecephys.nwb', 'size': 0, 'updated': '2020-11-05T16:57:52.589000+00:00'}                                                                                                                                                                                                                                                                                           
2020-11-05T12:12:05-0500 [ERROR   ] backups2datalad.py Operation failed with exception:                                                                                                                                                                                                                                                                                                                            
Traceback (most recent call last):                                                                                                                                                                                                                                                                                                                                                                                 
  File "tools/backups2datalad.py", line 462, in dandi_logging                                                                                                                                                                                                                                                                                                                                                      
    yield logfile                                                                                                                                                                                                                                                                                                                                                                                                  
  File "tools/backups2datalad.py", line 242, in sync_dataset                                                                                                                                                                                                                                                                                                                                                       
    for a in assets:                                                                                                                                                                                                                                                                                                                                                                                               
  File "/home/dandi/proj/dandi/dandi-cli/dandi/girder.py", line 518, in <genexpr>                                                                                                                                                                                                                                                                                                                                  
    (                                                                                                                                                                                                                                                                                                                                                                                                              
  File "/home/dandi/proj/dandi/dandi-cli/dandi/utils.py", line 197, in flatten                                                                                                                                                                                                                                                                                                                                     
    yield from flattened(i)                                                                                                                                                                                                                                                                                                                                                                                        
  File "/home/dandi/proj/dandi/dandi-cli/dandi/utils.py", line 204, in flattened                                                                                                                                                                                                                                                                                                                                   
    return list(flatten(it))                                                                                                                                                                                                                                                                                                                                                                                       
  File "/home/dandi/proj/dandi/dandi-cli/dandi/utils.py", line 195, in flatten                                                                                                                                                                                                                                                                                                                                     
    for i in it:                                                                                                                                                                                                                                                                                                                                                                                                   
  File "/home/dandi/proj/dandi/dandi-cli/dandi/girder.py", line 470, in <genexpr>                                                                                                                                                                                                                                                                                                                                  
    files = (e for e in entities if e["type"] == "file")                                                                                                                                                                                                                                                                                                                                                           
  File "/home/dandi/proj/dandi/dandi-cli/dandi/girder.py", line 272, in traverse_asset                                                                                                                                                                                                                                                                                                                             
    yield from self._traverse_asset_girder(g, parent_path, recursive=recursive)                                                                                                                                                                                                                                                                                                                                    
  File "/home/dandi/proj/dandi/dandi-cli/dandi/girder.py", line 315, in _traverse_asset_girder                                                                                                                                                                                                                                                                                                                     
    for child_a in self._traverse_asset_girder(child, a["path"]):                                                                                                                                                                                                                                                                                                                                                  
  File "/home/dandi/proj/dandi/dandi-cli/dandi/girder.py", line 315, in _traverse_asset_girder                                                                                                                                                                                                                                                                                                                     
    for child_a in self._traverse_asset_girder(child, a["path"]):                                                                                                                                                                                                                                                                                                                                                  
  File "/home/dandi/proj/dandi/dandi-cli/dandi/girder.py", line 289, in _traverse_asset_girder                                                                                                                                                                                                                                                                                                                     
    raise ValueError(                                                                                                                                                                                                                                                                                                                                                                                              
ValueError: multiple files per item not yet supported (if ever will be). Got: [{'_id': '5fa42f89271e91aad754e4bc', '_modelType': 'file', 'created': '2020-11-05T16:59:53.675000+00:00', 'creatorId': '5ee6c160155e470d51c94881', 'exts': ['nwb'], 'itemId': '5fa42d99271e91aad754e4a4', 'mimeType': 'application/octet-stream', 'name': 'sub-YutaMouse23_ses-YutaMouse23-140804_behavior+ecephys.nwb', 'size':     
7482132601}, {'_id': '5fa431f2271e91aad754e4c0', '_modelType': 'file', 'created': '2020-11-05T17:10:10.478000+00:00', 'creatorId': '5ee6c160155e470d51c94881', 'exts': ['nwb'], 'itemId': '5fa42d99271e91aad754e4a4', 'mimeType': 'application/octet-stream', 'name': 'sub-YutaMouse23_ses-YutaMouse23-140804_behavior+ecephys.nwb', 'size': 7482132601}]                                                          
Traceback (most recent call last):                                                                                                                                                                                                                                                                                                                                                                                 
  File "tools/backups2datalad.py", line 471, in <module>                                                                                                                                                                                                                                                                                                                                                           
    main()                                                                                                                                                                                                                                                                                                                                                                                                         
  File "/home/dandi/miniconda3/envs/dandi-cli-dev/lib/python3.8/site-packages/click/core.py", line 829, in __call__                                                                                                                                                                                                                                                                                                
    return self.main(*args, **kwargs)                                                                                                                                                                                                                                                                                                                                                                              
  File "/home/dandi/miniconda3/envs/dandi-cli-dev/lib/python3.8/site-packages/click/core.py", line 782, in main                                                                                                                                                                                                                                                                                                    
    rv = self.invoke(ctx)                                                                                                                                                                                                                                                                                                                                                                                          
  File "/home/dandi/miniconda3/envs/dandi-cli-dev/lib/python3.8/site-packages/click/core.py", line 1066, in invoke                                                                                                                                                                                                                                                                                                 
    return ctx.invoke(self.callback, **ctx.params)                                                                                                                                                                                                                                                                                                                                                                 
  File "/home/dandi/miniconda3/envs/dandi-cli-dev/lib/python3.8/site-packages/click/core.py", line 610, in invoke                                                                                                                                                                                                                                                                                                  
    return callback(*args, **kwargs)                                                                                                                                                                                                                                                                                                                                                                               
  File "tools/backups2datalad.py", line 96, in main                                                                                                                                                                                                                                                                                                                                                                
    DatasetInstantiator(                                                                                                                                                                                                                                                                                                                                                                                           
  File "tools/backups2datalad.py", line 170, in run                                                                                                                                                                                                                                                                                                                                                                
    if self.sync_dataset(did, ds):                                                                                                                                                                                                                                                                                                                                                                                 
  File "tools/backups2datalad.py", line 242, in sync_dataset                                                                                                                                                                                                                                                                                                                                                       
    for a in assets:                                                                                                                                                                                                                                                                                                                                                                                               
  File "/home/dandi/proj/dandi/dandi-cli/dandi/girder.py", line 518, in <genexpr>                                                                                                                                                                                                                                                                                                                                  
    (                                                                                                                                                                                                                                                                                                                                                                                                              
  File "/home/dandi/proj/dandi/dandi-cli/dandi/utils.py", line 197, in flatten                                                                                                                                                                                                                                                                                                                                     
    yield from flattened(i)                                                                                                                                                                                                                                                                                                                                                                                        
  File "/home/dandi/proj/dandi/dandi-cli/dandi/utils.py", line 204, in flattened                                                                                                                                                                                                                                                                                                                                   
    return list(flatten(it))                                                                                                                                                                                                                                                                                                                                                                                       
  File "/home/dandi/proj/dandi/dandi-cli/dandi/utils.py", line 195, in flatten                                                                                                                                                                                                                                                                                                                                     
    for i in it:                                                                                                                                                                                                                                                                                                                                                                                                   
  File "/home/dandi/proj/dandi/dandi-cli/dandi/girder.py", line 470, in <genexpr>                                                                                                                                                                                                                                                                                                                                  
    files = (e for e in entities if e["type"] == "file")                                                                                                                                                                                                                                                                                                                                                           
  File "/home/dandi/proj/dandi/dandi-cli/dandi/girder.py", line 272, in traverse_asset                                                                                                                                                                                                                                                                                                                             
    yield from self._traverse_asset_girder(g, parent_path, recursive=recursive)                                                                                                                                                                                                                                                                                                                                    
  File "/home/dandi/proj/dandi/dandi-cli/dandi/girder.py", line 315, in _traverse_asset_girder                                                                                                                                                                                                                                                                                                                     
    for child_a in self._traverse_asset_girder(child, a["path"]):                                                                                                                                                                                                                                                                                                                                                  
  File "/home/dandi/proj/dandi/dandi-cli/dandi/girder.py", line 315, in _traverse_asset_girder                                                                                                                                                                                                                                                                                                                     
    for child_a in self._traverse_asset_girder(child, a["path"]):                                                                                                                                                                                                                                                                                                                                                  
  File "/home/dandi/proj/dandi/dandi-cli/dandi/girder.py", line 289, in _traverse_asset_girder                                                                                                                                                                                                                                                                                                                     
    raise ValueError(                                                                                                                                                                                                                                                                                                                                                                                              
ValueError: multiple files per item not yet supported (if ever will be). Got: [{'_id': '5fa42f89271e91aad754e4bc', '_modelType': 'file', 'created': '2020-11-05T16:59:53.675000+00:00', 'creatorId': '5ee6c160155e470d51c94881', 'exts': ['nwb'], 'itemId': '5fa42d99271e91aad754e4a4', 'mimeType': 'application/octet-stream', 'name': 'sub-YutaMouse23_ses-YutaMouse23-140804_behavior+ecephys.nwb', 'size':     
7482132601}, {'_id': '5fa431f2271e91aad754e4c0', '_modelType': 'file', 'created': '2020-11-05T17:10:10.478000+00:00', 'creatorId': '5ee6c160155e470d51c94881', 'exts': ['nwb'], 'itemId': '5fa42d99271e91aad754e4a4', 'mimeType': 'application/octet-stream', 'name': 'sub-YutaMouse23_ses-YutaMouse23-140804_behavior+ecephys.nwb', 'size': 7482132601}]         
```
</details>

Even though in the case of new API this shouldn't happen, I think we should fixup current code to avoid that - probably, if girder would always have first file to be the older one, warn that there are multiple (not error) and proceed with the first one.

### PR DESCRIPTION
**Pull request by jwodder**
Fixes #264.

### CODE REVIEW

**Review by yarikoptic — APPROVED** [review]
Looks good and didn't break any test, so good to go - merge whenever we are ready to "auto-release".  I meanwhile will try it on drogon

**Comment by jwodder** [comment]
@yarikoptic Oops — I merged this, but forgot that #257 wasn't merged yet (It is now).  Is there another quick PR we could merge to try out a release?

**Comment by yarikoptic** [comment]
nothing comes to mind... I guess there should be some provisioning for that with this setup to just trigger a release from current master? if not -- just make some nonimportant PR (some tune up to formatting of CHANGELOG or README or whatnot)

**Comment by jwodder** [comment]
@yarikoptic PR made and release triggered successfully!

**Comment by yarikoptic** [comment]
whoohoo -- I see 0.7.1 on https://pypi.org/project/dandi/ !

**Comment by yarikoptic** [comment]
and a nice CHANGELOG! awesome.  
I wonder -- could we make sure that no PR is unlabeled "properly"? or is that already done?

**Comment by jwodder** [comment]
@yarikoptic PRs without labels default to the "Bug Fix" category, though I believe it can be changed to a different category.  Is that what you're asking?

**Comment by yarikoptic** [comment]
I thought: would be nice if bot reported "failed" state (so people do not merge) for the PR until some needed label(s) were added (something like WIP bot does if there is a label WIP present)

**Comment by jwodder** [comment]
@yarikoptic It doesn't do that.  Searching a bit, the only thing I can find that does do that is [dimagi/required-labels](https://github.com/dimagi/required-labels), which we would have to host somewhere.

**Comment by yarikoptic** [comment]
ok, let's just look after each other to not forget proper labeling

**Pull request merged**
