### PR TITLE
Adjust RemoteAsset.json_dict()

### LINKED ISSUE #690: API design: tune up asset structure/records
further tuning up backups2datalad.py to make it work, noted that assets records now contain 
```
(git)lena:~/proj/dandi/dandi-cli-master[master]git
$> python -c 'import dandi; print(dandi.__version__); from dandi.dandiapi import DandiAPIClient; ds = DandiAPIClient().get_dandiset("000027", "draft"); print([a.json_dict() for a in ds.get_assets()])'         
0.21.0+14.g0a2903f
[{'dandiset_id': '000027', 'version_id': 'draft', 'asset_id': 'ff453f4c-a435-4a5d-a48b-128abca5ec47', 'path': 'sub-RAT123/sub-RAT123.nwb', 'size': 18792, 'modified': datetime.datetime(2021, 5, 18, 13, 13, 56, 247883, tzinfo=datetime.timezone.utc)}]
```

1. information about dandiset (dandiset_id, version_id) - I think we should aim to have asset decoupled from a dandiset. dandi-api doesn't provide dandiset information upon `/assets`, and eventually assets might get shared by multiple dandisets
2. `modified` is datetime (not str), despite `json_dict` somewhat suggesting that it would be json-digestable dict, but datetime causes json to puke upon dumps.  I think for `json_dict` it should be serialized into str.

### PR DESCRIPTION
**Pull request by jwodder**
Closes #690.

### CODE REVIEW

**Comment by jwodder** [comment]
The tests are failing because of https://github.com/dandi/dandi-api/issues/380.

**Comment by yarikoptic** [comment]
WDYT about `datetime` (the `2.` of #690)?

**Comment by jwodder** [comment]
@yarikoptic The field should be a string in ISO 8601 format now.

**Comment by yarikoptic** [comment]
oh, I missed that check in the tests, thanks!

**Comment by yarikoptic** [comment]
Let's proceed despite our shameful red colors ;-) and I will release with #687 since we would need newer schema

**Pull request merged**
