### PR TITLE
Increase minimum dandischema version to 0.2.9

### PR DESCRIPTION
**Pull request by jwodder**
As requested by @satra on Slack.

### CODE REVIEW

**Review by satra — APPROVED** [review]

**Comment by satra** [comment]
in this or a separate PR, shall we also mark previous versions of CLI as bad in the .et file?

**Comment by jwodder** [comment]
The tests are failing because the asset in Dandiset 000027 no longer has a `contentUrl` field in its metadata.

@dchiquito Is that supposed to happen?

**Comment by satra** [comment]
@jwodder - assets have not been updated so they are not conformant. that depends on our out of band asset metadata update via the CLI. we can retrigger this after 27 is updated.

**Comment by yarikoptic** [comment]
<details>
<summary>I have "force" uploaded the only asset in 000027</summary> 

```shell
(dandisets) dandi@drogon:/mnt/backup/dandi/dandisets/000027$ dandi upload --validation ignore --existing=force
Please provide API Key for dandi: YARIKWASNOTANIDIOTTHISTIME
2021-06-29 18:59:28,931 [    INFO] Found 2 files to consider
PATH                      SIZE       ERRORS     UPLOAD STATUS                MESSAGE                      
dandiset.yaml             2.0 kB                       skipped               should be edited online      
sub-RAT123/sub-RAT123.nwb 18.8 kB       1              done                  exists (same) - reuploading  
Summary:                  20.8 kB 1 with errors        1 skipped             1 should be edited online    
                                                       1 done                1 exists (same) - reuploading
2021-06-29 18:59:29,740 [    INFO] Logs saved in /home/dandi/.cache/dandi-cli/log/20210629225858Z-21405.log
(dandisets) dandi@drogon:/mnt/backup/dandi/dandisets/000027$ dandi --version
0.21.0

```
</details>

<details>
<summary>which populated new metadata record which has contentUrls</summary> 

```shell
{
  "id": "dandiasset:1c095f5f-d1e2-45db-b807-fdcfea08c6de",
  "path": "sub-RAT123/sub-RAT123.nwb",
  "access": [
    {
      "status": "dandi:OpenAccess",
      "schemaKey": "AccessRequirements"
    }
  ],
  "digest": {
    "dandi:sha2-256": "1a765509384ea96b7b12136353d9c5b94f23d764ad0431e049197f7875eb352c",
    "dandi:dandi-etag": "6ec084ca9d3be17ec194a8f700d65344-1"
  },
  "@context": "https://raw.githubusercontent.com/dandi/schema/master/releases/0.4.4/context.json",
  "approach": [],
  "schemaKey": "Asset",
  "contentUrl": [
    "https://api.dandiarchive.org/api/assets/1c095f5f-d1e2-45db-b807-fdcfea08c6de/download/",
    "https://dandiarchive.s3.amazonaws.com/blobs/2db/af0/2dbaf0fd-5003-4a0a-b4c0-bc8cdbdb3826"
  ],
  "identifier": "1c095f5f-d1e2-45db-b807-fdcfea08c6de",
  "repository": "https://dandiarchive.org/",
  "contentSize": 18792,
  "dateModified": "2021-06-29T18:59:29.491552-04:00",
  "schemaVersion": "0.4.4",
  "encodingFormat": "application/x-nwb",
  "wasGeneratedBy": [
    {
      "id": "urn:uuid:e664a279-71dc-4290-9bb1-1c843e2b19cf",
      "name": "Metadata generation",
      "schemaKey": "Activity",
      "description": "Metadata generated by DANDI cli",
      "wasAssociatedWith": [
        {
          "url": "https://github.com/dandi/dandi-cli",
          "name": "DANDI Command Line Interface",
          "version": "0.21.0",
          "schemaKey": "Software",
          "identifier": "RRID:SCR_019009"
        }
      ]
    }
  ],
  "wasAttributedTo": [
    {
      "age": {
        "value": "P12M",
        "unitText": "Years from birth",
        "schemaKey": "PropertyValue"
      },
      "sex": {
        "name": "Male",
        "schemaKey": "SexType",
        "identifier": "http://purl.obolibrary.org/obo/PATO_0000384"
      },
      "species": {
        "name": "Brown rat",
        "schemaKey": "SpeciesType",
        "identifier": "http://purl.obolibrary.org/obo/NCBITaxon_10116"
      },
      "genotype": "WT",
      "schemaKey": "Participant",
      "identifier": "RAT123"
    }
  ],
  "blobDateModified": "2020-10-21T10:10:35.457789-04:00",
  "variableMeasured": [],
  "measurementTechnique": []
}

```
</details>

I will now push something to this PR to see things turn green (hopefully) ;)

**Comment by yarikoptic** [comment]
didn't check if actually 0.18.0 is good enough to inform that dandi-api requested schema version is good enough, but overall -- we shouldn't "abuse" `.et` for announcing prior versions are bad if it is just a matter of compatibility with the api server, which does provide schema_verison and supposed to provide its own api version.

**Comment by satra** [comment]
but dandi cli prior to this PR will not require schema_version 0.4.4. i'm not sure what the error message or any will be.

**Comment by yarikoptic** [comment]
> but dandi cli prior to this PR will not require schema_version 0.4.4. i'm not sure what the error message or any will be.

people would still be able to `download`,`organize` etc.  It is only `upload` which requires newer version, and then `dandi-api` should inform that it needs a newer schema version, and if so `dandi-cli` should fail informatively (didn't check if does) that it would need an upgrade to support that version.

**Comment by yarikoptic** [comment]
we hardcoded asset UUID , and thus still failing.  Moreover we got `/assets` end point which is what is now returned by dandi-api  instead of per-dandiset asset `/download` endpoint.  I adjusted the test to not hardcode UUID and just test for a correct (adjusted) endpoint.

**Comment by yarikoptic** [comment]
new fiasco: https://github.com/dandi/dandi-api/issues/380 .  Since I think it should be just fixed, and nothing to be done in dandi-cli... the other failing (erroring out) test seems to be 3.7 specific:

```
(dandisets) dandi@drogon:~/cronlib/tinuous-logs/dandi-cli/2021/06/29/github/pr/687/04a35df$ git grep 'Z FAILED' | grep -v test_get_content_url_follow_one_redirects
Tests/2638/10_test (ubuntu-18.04, 3.7, dev-deps).txt:2021-06-29T23:52:31.7310222Z FAILED
Tests/2638/10_test (ubuntu-18.04, 3.7, dev-deps).txt:2021-06-29T23:53:59.7088324Z FAILED dandi/tests/test_dandiapi.py::test_publish_and_manipulate - ValueError...
Tests/2638/3_test (ubuntu-18.04, 3.7, normal).txt:2021-06-29T23:52:14.7496953Z FAILED
Tests/2638/3_test (ubuntu-18.04, 3.7, normal).txt:2021-06-29T23:53:32.0091087Z FAILED dandi/tests/test_dandiapi.py::test_publish_and_manipulate - ValueError...
Tests/2638/test (ubuntu-18.04, 3.7, dev-deps)/9_Run all tests.txt:2021-06-29T23:52:31.7310208Z FAILED
Tests/2638/test (ubuntu-18.04, 3.7, dev-deps)/9_Run all tests.txt:2021-06-29T23:53:59.7088284Z FAILED dandi/tests/test_dandiapi.py::test_publish_and_manipulate - ValueError...
Tests/2638/test (ubuntu-18.04, 3.7, normal)/9_Run all tests.txt:2021-06-29T23:52:14.7496942Z FAILED
Tests/2638/test (ubuntu-18.04, 3.7, normal)/9_Run all tests.txt:2021-06-29T23:53:32.0091076Z FAILED dandi/tests/test_dandiapi.py::test_publish_and_manipulate - ValueError...
```
and in a nutshell:
```
2021-06-29T23:53:59.6712575Z _________________________ test_publish_and_manipulate __________________________
2021-06-29T23:53:59.6715000Z /home/runner/work/dandi-cli/dandi-cli/dandi/tests/test_dandiapi.py:67: in test_publish_and_manipulate
2021-06-29T23:53:59.6716681Z     version_id = d.publish().version.identifier
2021-06-29T23:53:59.6718444Z /home/runner/work/dandi-cli/dandi-cli/dandi/dandiapi.py:436: in publish
2021-06-29T23:53:59.6722586Z     f"Dandiset {self.identifier} is invalid: {r['validation_error']}"
2021-06-29T23:53:59.6723914Z E   ValueError: Dandiset 000002 is invalid:
```
but smells like that h5py may be raising some other exception from what we expect or smth like that... also unrelated IMHO to these changes but I fail to grasp yet why it started to fail now and only for 3.7

**Comment by yarikoptic** [comment]
I would prefer to resolve those issues before merge/release but if this holds up anything, feel free to "Merge" @satra

**Pull request merged**
