### PR TITLE
Configure CI to run flake8

### PR DESCRIPTION
**Pull request by jwodder**
PR #144 is a prerequisite for this.  (In the future, when PR x depends on PR y, would you prefer it if x's branch extended y's or not?)

### CODE REVIEW

**Comment by yarikoptic** [comment]
> In the future, when PR x depends on PR y, would you prefer it if x's branch extended y's or not?

yes, probably to "extend y" so later on, when we need to `git bisect` etc there is lesser chance to end up in a false positive "failing state"

**Comment by yarikoptic** [comment]
I have restarted the CI job since #144 was merged. Came out red.
I guess we need to provide this specific linter with the settings we use for pre-commit/black. We already specify some (max width) in setup.cfg for flake8:
```
[flake8]
max-line-length = 100
```

**Comment by yarikoptic** [comment]
ignore above -- I only now saw #147 ;)

**Comment by yarikoptic** [comment]
could you please rebase on top of master and force push?  Would be nice to get it green to know that we could safely merge

**Comment by jwodder** [comment]
Done, though I don't believe it'll be green until after #147 is merged.

**Comment by yarikoptic** [comment]
#147 is merged now ;) Thanks!

**Comment by yarikoptic** [comment]
all green on rerunning the pull request run -- so good to go AFAIK

**Pull request merged**
