### PR TITLE
Further improve README.md: point to specific sections of handbook, remove lengthy `dandi ls --help` example

### PR DESCRIPTION
**Pull request by melster1010**
address 3 items outstanding from review in PR #1170

### CODE REVIEW

**Comment by yarikoptic** [comment]
well, although I agree that sample output of `--help` commands can get outdated, I think I do like seeing them in README.md since it gives an immediate overview of exposed by the client functionality.  If it is outdated already -- then updates are welcome for those parts.

**Comment by melster1010** [comment]
> well, although I agree that sample output of `--help` commands can get outdated, I think I do like seeing them in README.md since it gives an immediate overview of exposed by the client functionality. If it is outdated already -- then updates are welcome for those parts.

After removing all of the UI graphics it does seem empty, and I understand that it would be useful to see _something_ in the readme prior to using the tool...so I restored the first UI graphic of the initial interface but left out the other one for the help output, so a compromise! :)

**Review by waxlamp — COMMENTED** [review]
I think we should remove the listing of the dandi CLI help output and perhaps replace it with a few examples of common use cases for the tool. Let me know what you think of that.

**Comment by melster1010** [comment]
> I think we should remove the listing of the dandi CLI help output and perhaps replace it with a few examples of common use cases for the tool. Let me know what you think of that.

I like that suggestion a lot, showing the UI and a couple of examples as done [here](https://github.com/francisrstokes/readme-cli). Which commands would be best to showcase, download and upload perhaps?

**Comment by yarikoptic** [comment]
Attn @melster1010  -- I changed the PR description to summarize changes since it would become a part of the changelog, so should be aiming at the user/worthy appearing in changelog.

**Pull request merged**
