### PR TITLE
Add `get_assets_by_glob()`

### LINKED ISSUE #979: add glob/regex support in the dandi library
now that the api has support for glob/regex options in the `GET` for dandiset specific assets (endpoint: `/dandisets/{versions__dandiset__pk}/versions/{versions__version}/assets/`), it would be nice to have this option at least in the python library and perhaps in the cli for `ls`

### PR DESCRIPTION
**Pull request by jwodder**
Closes #979.

### CODE REVIEW

**Comment by satra** [comment]
is this held up on anything?

**Comment by jwodder** [comment]
@satra It's blocked by https://github.com/dandi/dandi-archive/issues/1047.

**Comment by jwodder** [comment]
@yarikoptic This is ready to be merged.

**Comment by yarikoptic** [comment]
So let's make it happen! Thank you @jwodder

**Pull request merged**
