### PR TITLE
Update Docker Compose spin-up code for loss of --username option

### PR DESCRIPTION
**Pull request by jwodder**
See https://github.com/dandi/dandischema/issues/82 for more information.

Until the next rebuild of the dandi-api image on the Docker Hub, this PR will make dandi-cli's tests fail, so don't merge until then.  Once it's merged, the dandi-cli integration tests for dandischema (for the master version of dandi-cli, not the released version) will start passing again.

### CODE REVIEW

**Comment by yarikoptic** [comment]
> Until the next rebuild of the dandi-api image on the Docker Hub

so I just should trigger rebuild ? triggered on https://hub.docker.com/repository/docker/dandiarchive/dandiarchive-api/builds

**Comment by jwodder** [comment]
@yarikoptic The tests pass now.

**Comment by yarikoptic** [comment]
AWESOME! Let's cherish the moment with the merge. Thank you @jwodder !

**Comment by yarikoptic** [comment]
IIRC we might be testing against released version, so I will also mark this for release

**Pull request merged**
