### PR TITLE
Update for fix to Zarr upload procedure

### PR DESCRIPTION
**Pull request by jwodder**
Blocked by https://github.com/dandi/dandi-archive/pull/1497.

### CODE REVIEW

**Comment by jwodder** [comment]
@yarikoptic The dandi-archive PR has been merged, so this PR should be merged & released soon.  Do you want to first somehow test this against staging this time?

**Comment by AlmightyYakob** [comment]
According to S3, the `Content-MD5` header must contain the following:

> The base64-encoded 128-bit MD5 digest of the message


Can you try this again, but in the `digest` field, encode it with base64 instead of a hexdigest? If we confirm this is the issue, we can rename the `digest` field to `base64digest` or something, to make it more clear.

**Comment by jwodder** [comment]
@AlmightyYakob Do you mean the `"md5"` field in the `../files/` request body?

**Comment by AlmightyYakob** [comment]
> @AlmightyYakob Do you mean the `"md5"` field in the `../files/` request body?

Yes

**Comment by jwodder** [comment]
@AlmightyYakob That works.

**Comment by AlmightyYakob** [comment]
I've opened https://github.com/dandi/dandi-archive/pull/1498 to make the distinction clearer.

**Comment by AlmightyYakob** [comment]
> I've opened [dandi/dandi-archive#1498](https://github.com/dandi/dandi-archive/pull/1498) to make the distinction clearer.

This has been merged and is live on staging.

**Comment by jwodder** [comment]
@AlmightyYakob Are you sure it's live on staging?  I just tried uploading with this branch and got `Error 400 while sending POST request to https://api-staging.dandiarchive.org/api/zarr/e33f4348-a72d-413a-84f3-cb199a5bfb48/files/: [{"md5":["This field is required."]},{"md5":["This field is required."]}]`.

**Comment by jwodder** [comment]
@AlmightyYakob Staging is now working.  Can this be merged now?

**Pull request merged**
