### PR TITLE
Update `asset_validation_errors` structure

### PR DESCRIPTION
**Pull request by jwodder**
Part of/blocked by https://github.com/dandi/dandi-archive/pull/1579.

### CODE REVIEW

**Comment by jwodder** [comment]
@AlmightyYakob has requested that we merge this PR before the dandi-archive one.

**Comment by yarikoptic** [comment]
FWIW, ATM I remain questioning such a change in dandi-archive: https://github.com/dandi/dandi-archive/pull/1579#issuecomment-1557154515

**Comment by yarikoptic** [comment]
@jwodder please check that PR now given recent changes on either we would need any changes in dandi-cli.

**Comment by jwodder** [comment]
Closing in favor of #1303.

**Pull request closed without merging**
