### PR TITLE
Reuse "loose" Zarrs that conflict with uploaded path

### LINKED ISSUE #1034: "Zarr already exists" Error while uploading
I received the below error while trying to upload a file using the following command:

`DANDI_DEVEL=1 dandi upload --validation skip --allow-any-path /mnt/beegfs/Lee/dandi/sub-MITU01/ses-20220326h13m51s50/micr/sub-MITU01_ses-20220326h13m51s50_sample-10_stain-YO_run-1_chunk-4_SPIM.ome.zarr`

Full log attached below.

```
2022-06-29T10:34:15-0400 [ERROR   ] dandi 715731:140277145179904 Error 400 while sending POST request to https://api.dandiarchive.org/api/zarr/: ["Zarr already exists"]
2022-06-29T10:34:15-0400 [ERROR   ] dandi 715731:140277145179904 Error uploading /mnt/beegfs/Lee/dandi/sub-MITU01/ses-20220326h13m51s50/micr/sub-MITU01_ses-20220326h13m51s50_sample-10_stain-YO_run-1_chunk-4_SPIM.ome.zarr:
Traceback (most recent call last):
  File "/mnt/beegfs/satra/miniconda3/envs/dandi/lib/python3.8/site-packages/dandi/upload.py", line 232, in process_path
    for r in dfile.iter_upload(
  File "/mnt/beegfs/satra/miniconda3/envs/dandi/lib/python3.8/site-packages/dandi/files.py", line 838, in iter_upload
    r = client.post(
  File "/mnt/beegfs/satra/miniconda3/envs/dandi/lib/python3.8/site-packages/dandi/dandiapi.py", line 288, in post
    return self.request("POST", path, **kwargs)
  File "/mnt/beegfs/satra/miniconda3/envs/dandi/lib/python3.8/site-packages/dandi/dandiapi.py", line 254, in request
    raise requests.HTTPError(msg, response=result)
requests.exceptions.HTTPError: Error 400 while sending POST request to https://api.dandiarchive.org/api/zarr/
2022-06-29T10:34:16-0400 [DEBUG   ] pyout.interface 715731:140277145179904 Received result for ('size', 'errors', 'upload', 'status', 'message'): {'status': 'ERROR', 'message': 'Error 400 while sending POST request to https://api.dandiarchive.org/api/zarr/'}

```

The file does not already exist within the dandi archive:
image

My dandi version is 41.0

Full Log:
[20220629143352Z-715731.log](https://github.com/dandi/dandi-cli/files/9011552/20220629143352Z-715731.log)

### PR DESCRIPTION
**Pull request by jwodder**
Fixes #1034.

### CODE REVIEW

**Comment by satra** [comment]
@slaytonmarx and i were just in a huddle and this didn't work. he will post the logs.

**Comment by jwodder** [comment]
@satra Did he try before or after the most recent commit?

**Comment by satra** [comment]
before i think.

**Comment by yarikoptic** [comment]
> > why only "part" and not fixes?
> 
> Because the issue shouldn't be closed until @slaytonmarx confirms the problem is fixed.

I think this would establish a somewhat new approach to handling issues.  AFAIK so far we mark issues Fixed if PR aims to address them, typically indeed with a confirmation via a test demonstrating original issue and/or confirmation by the user. I user comes later saying that issue was not fixed, we can always reopen. But not closing them with PRs opens opportunity for issues to linger around while already fixed and then needing extra triageing to figure out what "part" was addressed or not.  So IMHO this PR should aim to fix that issue entirely and be marked as such.

**Comment by slaytonmarx** [comment]
Attempting the load again. To make clear, I simply ran `python -m pip install -U git+https://github.com/dandi/dandi-cli.git@gh-1034` again, let me know if I need to go to a specific directory and pull to add the change. Will send error log if failure or confirm fixed if success.

**Comment by slaytonmarx** [comment]
The command has been hanging on this output. I've gotten a number of errors with the same files as before but the process hasn't died, do we know if it's hanging or is something going on under the hood? What output should I expect from this fix?

image

**Comment by slaytonmarx** [comment]
Here's the full log file:
https://drive.google.com/file/d/11u6PO5zTcRkUht239JUJlsMQxkmR6-bD/view?usp=sharing

**Comment by jwodder** [comment]
@slaytonmarx The 400's all appear to be caused by #1028.  If the other uploads are in the "comparing against remote Zarr" stage, then they've gotten past the point at which the "loose" Zarrs were causing errors.

**Comment by slaytonmarx** [comment]
Hurray! Thank you for the fix! Jumping back to 1028

**Comment by yarikoptic** [comment]
> Hurray! Thank you for the fix! Jumping back to 1028

@slaytonmarx please don't forget to update us if the original issue (unable to upload "loose" zarrs) is addressed with this PR so we could proceed with merge/release to ease access to the fixed functionality.

**Comment by yarikoptic** [comment]
well, I think that the logic is correct, tests were added, let's proceed and then possibly reopen issue if @slaytonmarx would confirm that it still persists.

**Comment by slaytonmarx** [comment]
I'll pull and try again!

**Comment by slaytonmarx** [comment]
I've gotten the error again, specifically the simultaneous uploads error. I pulled the most recent version and am running the same command as before.

image

Here's the log:
https://drive.google.com/file/d/1gF3oOG1uBdPPpybJTIyFtqsi0hfzMS9p/view?usp=sharing

(Thank you for all of this effort, I really do appreciate all of the work you and your team are doing trying to get through these bugs!)

**Comment by jwodder** [comment]
@slaytonmarx Simultaneous uploads are being addressed by #1028; this PR is for the "Zarr already exists" error.

**Comment by slaytonmarx** [comment]
Roger that, I'll move it over there. In regards to Zarr already exists, I can report that that error seems to have been resolved.

**Pull request merged**
