### PR TITLE
Eliminate DANDI_SCHEMA; add get_schema_version()

### LINKED ISSUE #430: fscache validation of the files (taking hdmf, h5py, pynwb, dandi versions as tokens)
to speed up reruns in dandi-api-datasets

### PR DESCRIPTION
**Pull request by jwodder**
Closes #430.

After merging this, merge https://github.com/dandi/dandi-api-datasets/pull/18.

### CODE REVIEW

**Comment by yarikoptic** [comment]
could you remind me @jwodder -- can we eliminate `push` CI runs for PRs?

**Review by yarikoptic — APPROVED** [review]
CI is still out for its verdict, but otherwise looks good

**Comment by jwodder** [comment]
@yarikoptic Not without eliminating all CI runs for all pushes for the affected workflow(s).  There doesn't seem to be a way to trigger a push run iff the push is not already part of a pull request.

**Comment by yarikoptic** [comment]
> EDIT: One option would be to limit push runs to just the master branch.

I think that is a good idea

**Comment by yarikoptic** [comment]
ok, let's ssume taht populate_dandiset_yaml would have succeeded and proceed. Thank you @jwodder

**Pull request merged**
