### PR TITLE
Adjust license metadata conversion

### LINKED ISSUE #362: dandiset metadata migration got broken
Initially reported by @AlmightyYakob on slack in `#internal` and reproduced

Running our script within https://github.com/dandi/dandi-api-datasets.git which converts metadata
```
(git-annex)lena:~/proj/dandi/dandi-api-datasets[master]git
$> datalad rerun
[INFO   ] run commit 01b6175; (convert/populate ...) 
[INFO   ] Making sure inputs are available (this may take some time) 
[INFO   ] == Command start (output follows) ===== 
dandisets/000003: EXCEPTION (000003/EXCEPTION) - C
dandisets/000004: EXCEPTION (000004/EXCEPTION) - C
dandisets/000005: EXCEPTION (000005/EXCEPTION) - C
dandisets/000006: EXCEPTION (000006/EXCEPTION) - C
dandisets/000007: EXCEPTION (000007/EXCEPTION) - C
dandisets/000008: EXCEPTION (000008/EXCEPTION) - C
dandisets/000009: EXCEPTION (000009/EXCEPTION) - C
dandisets/000010: EXCEPTION (000010/EXCEPTION) - C
...

$> cat 000003/EXCEPTION
Traceback (most recent call last):
  File "/home/yoh/proj/dandi/dandi-api-datasets/tools/populate_dandiset_yaml.py", line 34, in <module>
    new_meta = migrate2newschema(dandiset_meta)
  File "/home/yoh/proj/dandi/dandi-cli-master/dandi/metadata.py", line 535, in migrate2newschema
    newmeta = convertv1(meta)
  File "/home/yoh/proj/dandi/dandi-cli-master/dandi/metadata.py", line 430, in convertv1
    newvalues.append(getattr(models.LicenseType, val.split(":")[-1]))
  File "/usr/lib/python3.9/enum.py", line 352, in __getattr__
    raise AttributeError(name) from None
AttributeError: C
```

after addressed, would be nice to automate such a "check", so filed separate https://github.com/dandi/dandi-cli/issues/361

### PR DESCRIPTION
**Pull request by jwodder**
Fixes #362.

### CODE REVIEW

**Comment by satra** [comment]
LGTM. it may be worthwhile running this on all the dandiset.yaml files to make sure there are no other gotchas.

**Comment by jwodder** [comment]
@satra If I use this branch to run `populate_dandiset_yaml.py` on 000003, the same error as before occurs, as the `dandiset.yaml` file sets the `license` field to a single string, yet the code is expecting a list.  The same thing appears to be happening for Dandisets 000004 through 000011 and 000013 through 000017.  In addition, the script fails for Dandiset 000041 because its metadata contains the following:

```yaml
age:
  maximum: 3-7 months
  minimum: 3-7 months
  units: TODO
```

**Comment by satra** [comment]
for 41 we would need to build it into the age parser section, but i think we are dropping that field and planning to extract it from the assets.

for the list thing, could you please adjust the metadata converter to take a string and return a list? at present it will not have more than one entry. the list option was kept in case we decided to create a virtual dandiset with multiple licensing options.

**Comment by jwodder** [comment]
@satra Should the converter always assume the license is a string, or should it allow both string and list inputs?

**Comment by yarikoptic** [comment]
FWIW, I have merged #364 so if this PR is rebased we can see how well things fixup. 
For 000003 - I think we should just fix that in metadata on girder... but there is some discrepancy -- looking into WTF ATM.

**Comment by yarikoptic** [comment]
> discrepancy -- looking into WTF ATM.

it was a mental one ;)  so I made it into 
```
$> dandi ls http://dandiarchive.org/dandiset/000041
2021-02-04 16:30:15,055 [    INFO] Traversing remote dandisets (000041) recursively
- created: '2020-10-05T16:18:52.896000+00:00'
  metadata:
    age:
      maximum: 3
      minimum: 7
      units: months
```
and now running the script to update datalad datasets...

**Comment by yarikoptic** [comment]
hm still `dandisets/000003: EXCEPTION (000003/EXCEPTION) - C`

**Comment by satra** [comment]
> Should the converter always assume the license is a string

@jwodder - yes, there are no lists in the current girder metadata and the converter will go away once we remove girder.

**Comment by yarikoptic** [comment]
ok, besides coverage all green now, merging. Also pushed updated http://github.com/dandi/dandi-api-datasets

**Pull request merged**
