### PR TITLE
Trigger Zarr ingestion after performing an upload

### LINKED ISSUE #937: Updated Zarr Upload Process
Via https://github.com/dandi/dandi-archive/pull/960, the zarr upload process will be updated to perform ingestion separately from upload. The CLI needs to be updated to account for this.

Notable API changes:
* Add a status field to the ZarrArchive model (and retrieve endpoint), to indicate the ingestion status
* Remove checksum calculation as part of zarr upload completion
* Add a zarr ingest endpoint to begin the ingestion of a zarr archive
* Update the zarr file delete and upload cancel endpoints to fail if an ingestion is in progress

### PR DESCRIPTION
**Pull request by jwodder**
Blocked by https://github.com/dandi/dandi-archive/pull/960.

Closes #937.

### CODE REVIEW

**Comment by AlmightyYakob** [comment]
@jwodder https://github.com/dandi/dandi-archive/pull/960 has been updated to change the status of `Valid` to `Complete`.

**Comment by yarikoptic** [comment]
Dear @AlmightyYakob , thank you for the update. I guess we are just doomed to wait for the release and your next buzz, since otherwise we wouldn't be able to tell one deployed version from another to make behavior conditional on the version of API. (back ref: https://github.com/dandi/dandi-archive/issues/222)

**Comment by jwodder** [comment]
@yarikoptic Now that the dandi-archive PR has been merged, dandi-cli tests on master are failing because this PR isn't merged.

**Comment by jwodder** [comment]
@yarikoptic I tested uploading a 38 GB Zarr to staging using dandi 0.37.0.  This took 44 minutes; compare [the previous test](https://github.com/dandi/dandi-cli/pull/923#discussion_r814188637), which took 63 minutes.

* Approximately the first 90 seconds were spent traversing the Zarr filetree
* The calls to `/upload/complete/` started out very quick, but as the files in each batch grew in size, it started taking up to about 7 seconds.
* The ingestion at the end took about a minute and a half.

**Comment by satra** [comment]
i'm pinging @dchiquito on this. the `/upload/complete` endpoint should be fairly consistent in timing and independent of file size at this point, so there may be something that was overlooked on that side.

**Pull request merged**
