### PR TITLE
Support downloading folders and latest Dandiset version

### LINKED ISSUE #340: dandi-api: improve download functionality
TODOs
- [x] add support for downloading a specific folder (that was disabled)
- [x] replace hardcoded to consider "draft" to be the "latest version" . We should remove that and allow for version to be left unspecified, and then DandiAPIClient code handle it properly (get the latest version, download for it)

### PR DESCRIPTION
**Pull request by jwodder**
Closes #340.

### CODE REVIEW

**Comment by yarikoptic** [comment]
seems to still download the full dandiset even if location points to the directory and all the parsing seems to be done correctly (folder information is given etc; the same behavior with `'dandi://dandi-api/000027/sub-RAT123/' ` url)

```shell
$> dandi -l 2 download 'https://gui-beta-dandiarchive-org.netlify.app/#/dandiset/000027/0.210210.1541/files?location=sub-RAT123%2F'
2021-02-10 14:53:57,640 [   DEBUG] Running a newer version (0.10.0+138.gf2f2dab) of dandi/dandi-cli than available (0.10.0)
2021-02-10 14:53:57,966 [   DEBUG] Parsing url https://gui-beta-dandiarchive-org.netlify.app/#/dandiset/000027/0.210210.1541/files?location=sub-RAT123%2F
2021-02-10 14:53:57,967 [ Level 5] Matched 'https://gui-beta-dandiarchive-org.netlify.app/#/dandiset/000027/0.210210.1541/files?location=sub-RAT123%2F' into {'server': 'https://gui-beta-dandiarchive-org.netlify.app/', 'protocol': 'https', 'hostname': 'gui-beta-dandiarchive-org.netlify.app', 'asset_type': 'dandiset', 'dandiset_id': '000027', 'version': '0.210210.1541', 'location': 'sub-RAT123%2F'}
2021-02-10 14:53:57,967 [   DEBUG] Parsed into ('api', 'https://api.dandiarchive.org/api/', 'folder', {'dandiset_id': '000027', 'version': '0.210210.1541', 'location': 'sub-RAT123/'})
2021-02-10 14:53:57,967 [   DEBUG] GET https://api.dandiarchive.org/api/dandisets/000027/versions/0.210210.1541/
2021-02-10 14:53:58,301 [   DEBUG] Response: 200
2021-02-10 14:53:58,301 [   DEBUG] Found identifier 000027 in 'dandiset.identifier'
PATH                 SIZE DONE    DONE% CHECKSUM STATUS MESSAGE   
dandiset.yaml                                           updating  
Summary:                  0 Bytes                       1 updating
dandiset.yaml                                    done   updated   
PATH                      SIZE     DONE    DONE% CHECKSUM STATUS        MESSAGE   
dandiset.yaml                                             done          updated   
sub-RAT123/sub-RAT123.nwb 18.8 kB                         downloading             
PATH                      SIZE     DONE    DONE% CHECKSUM STATUS          MESSAGE   
dandiset.yaml                                             done            updated   
sub-RAT123/sub-RAT123.nwb 18.8 kB  18.8 kB  100%    ok    done                      
Summary:                  18.8 kB  18.8 kB                2 done          1 updated 
                                   100.00%                                          
2021-02-10 14:53:59,244 [    INFO] Logs saved in /home/yoh/.cache/dandi-cli/log/20210210195357Z-2287093.log
(dev3) 1 56926.....................................:Wed 10 Feb 2021 02:53:59 PM EST:.
lena:/tmp
$> ls -l sub-RAT123                                                                                                               
ls: cannot access 'sub-RAT123': No such file or directory
(dev3) 1 56927 ->2.....................................:Wed 10 Feb 2021 02:54:35 PM EST:.
lena:/tmp
$> ls -l 000027    
total 8
-rw------- 1 yoh yoh  694 Feb 10 14:53 dandiset.yaml
drwx------ 2 yoh yoh 4096 Feb 10 14:53 sub-RAT123/
```

FWIW, girder based one seems to do it "right":
```
$> dandi download 'https://gui.dandiarchive.org/#/dandiset/000027/draft/files?_id=5f176583f63d62e1dbd06943&_modelType=folder'
2021-02-10 14:56:01,156 [    INFO] Traversing remote folders (sub-RAT123) recursively
PATH                      SIZE     DONE    DONE% CHECKSUM STATUS          MESSAGE
sub-RAT123/sub-RAT123.nwb 18.8 kB  18.8 kB  100%    ok    done                   
Summary:                  18.8 kB  18.8 kB                1 done                 
                                   100.00%                                       
2021-02-10 14:56:02,070 [    INFO] Logs saved in /home/yoh/.cache/dandi-cli/log/20210210195600Z-2288182.log
(dev3) 1 56930.....................................:Wed 10 Feb 2021 02:56:02 PM EST:.
lena:/tmp
$> ls -l 000027                                                                                                              
ls: cannot access '000027': No such file or directory
(dev3) 1 56931 ->2.....................................:Wed 10 Feb 2021 02:56:06 PM EST:.
lena:/tmp
$> ls -l sub-RAT123                                                                     
total 20
-rw------- 1 yoh yoh 18792 Jul 21  2020 sub-RAT123.nwb
```
```

**Comment by jwodder** [comment]
@yarikoptic Dandiset 000027 only contains a `sub-RAT123/` folder, so specifying just that folder won't make a difference.  Try with something with multiple folders, like 000056.

Or is your concern about the presence of the `dandiset.yaml` file?  Currently, that will always be created, no matter how many files are downloaded.

**Comment by yarikoptic** [comment]
gotcha -- we should change that: if user asks to download a folder or a file, we should just download that folder or file and not leading to it dandiset and its dandiset.yaml.  Possible use cases - me collating files from different dandisets. So it should be pretty much how we do ATM for girder based instance as I have demonstrated above.

**Comment by jwodder** [comment]
@yarikoptic Behavior changed.

**Pull request merged**
