### PR TITLE
Use upstream bidsschematools for BIDS validation

### PR DESCRIPTION
**Pull request by TheChymera**
The package is not officially released yet, but better start preparing now. Will also help figure out compatibility issues so we can try to fix them upstream before release.

Supersedes: https://github.com/dandi/dandi-cli/pull/1093

### CODE REVIEW

**Comment by TheChymera** [comment]
The package [has been released last week](https://pypi.org/project/bidsschematools/#history), so hopefully we can depend on it via pypi.

**Comment by TheChymera** [comment]
@yarikoptic looks good?

**Comment by TheChymera** [comment]
Actually, don't review quite yet, I think I broke something with the last merge. It seems to only run one test :-/

**Comment by TheChymera** [comment]
@yarikoptic @yarikoptic ok, I fixed what I had messed up yesterday. Interested in merging?

**Review by jwodder — APPROVED** [review]

**Pull request merged**
