### PR TITLE
ENH: ls - hide empty columns; --format to choose output format

### LINKED ISSUE #25: ls: alternative output formats
we would like to be able to spit out metadata in alternative formats/renderings
- json
- json_pp (pretty printed) (both might be not a single json record, but rather [json lines](http://jsonlines.org/) stream)
- yaml (may be when/if interest/demand)
- pandas dataframe rendering (will require obtaining all records first)

### PR DESCRIPTION
**Pull request by yarikoptic**
https://github.com/pyout/pyout/pull/86 is to add ability to hide columns which had no value in any of the rows.  This way we could aim to display the pertinent extended list of columns/metadata for the files at hand.
Overall - it works! formatting is a bit off, will report in pyout PR

By mistake pushed here also `--format` (Closes #25), and decided to just let it be here.  Unless there would be a need, let's proceed with changes "in bulk"

TODOs:
- [ ] wait for pyout release, adjust version in setup.cfg

### CODE REVIEW

**Comment by satra** [comment]
@yarikoptic - could we do the output like pandas if it isn't already the case? 

if multiple files, show columns, if single file, show key-value pairs in rows

**Comment by yarikoptic** [comment]
> @yarikoptic - could we do the output like pandas if it isn't already the case?
> 
> if multiple files, show columns, if single file, show key-value pairs in rows

not yet -- "formalized" into #25

**Comment by yarikoptic** [comment]
@satra now with `--format` support here too. `json_pp` is somewhat of invalid json since I am spitting each record at a time... may be we will wrap it into a list of things later on or decide to use `path` as a key anyways.  So for a prototype it should suffice.  Now I observe:

```shell
(git)hopa:~/proj/dandi/dandi-cli[enh-pyout-rules-empty-columns]git
$> dandi ls /tmp/nwb_test_data/v2.0.1/test_Cluster*                       
PATH                                                SIZE    IDENTIFIER            SESSION_DESCRIPTION                                   SESSION_START_TIME   NWB 
/tmp/nwb_test_data/v2.0.1/test_Clustering.nwb       17.8 kB TEST_Clustering       a file to test writing and reading a Clustering       1971-01-01/12:00:00  2.0b
/tmp/nwb_test_data/v2.0.1/test_ClusterWaveforms.nwb 20.0 kB TEST_ClusterWaveforms a file to test writing and reading a ClusterWaveforms 1971-01-01/12:00:00  2.0b
Summary:                                            37.7 kB                                                                             1971-01-01/12:00:00>     
                                                                                                                                        1971-01-01/12:00:00<     

$> dandi ls /tmp/nwb_test_data/v2.0.1/test_Clustering.nwb 
- identifier: TEST_Clustering
  nwb_version: 2.0b
  path: /tmp/nwb_test_data/v2.0.1/test_Clustering.nwb
  session_description: a file to test writing and reading a Clustering
  session_start_time: 1971-01-01 12:00:00+00:00
  size: 17752
```

**Comment by yarikoptic** [comment]
BTW @mgrauer if you need to get metadata records quickly, as a json lines stream:
```shell
$> dandi ls -f json /tmp/nwb_test_data/v2.0.1/test_Cluster*      
{"path": "/tmp/nwb_test_data/v2.0.1/test_Clustering.nwb", "size": 17752, "nwb_version": "2.0b", "identifier": "TEST_Clustering", "session_description": "a file to test writing and reading a Clustering", "session_start_time": "1971-01-01 12:00:00+00:00"}
{"path": "/tmp/nwb_test_data/v2.0.1/test_ClusterWaveforms.nwb", "size": 19976, "nwb_version": "2.0b", "identifier": "TEST_ClusterWaveforms", "session_description": "a file to test writing and reading a ClusterWaveforms", "session_start_time": "1971-01-01 12:00:00+00:00"}
```

**Comment by yarikoptic** [comment]
ok, testing is going but there is some problem with "yaml" formatting since it fails smoke testing for `ls` on a single file and explicit test with format yaml

PS there is also some incorrect handling by click's `CliRunner.invoke` but I am yet to research/file an issue.

**Comment by yarikoptic** [comment]
@bendichter @mgrauer could you try running tests on this branch locally in your env? To get pytest etc installed, `pip install -e .[test]`

**Comment by yarikoptic** [comment]
Just FTR, the click issue affecting my ability to troubleshoot is that it is not easy (impossible) to report stderr: https://github.com/pallets/click/pull/1194

**Comment by yarikoptic** [comment]
woohoo -- we are green! it was missing `pyyaml` dependency! I will merge and tag since it is some kind of a progress and it should work without not yet released pyout (sensing was added for `hide` to be available)

**Pull request merged**
