### PR TITLE
Add `DANDI_TESTS_PULL_DOCKER_COMPOSE` envvar

### LINKED ISSUE #1140: Add env var to disable docker-compose pull in the fixture
We already have `DANDI_TESTS_PERSIST_DOCKER_COMPOSE` and let's add `DANDI_TESTS_PULL_DOCKER_COMPOSE` (or anything else really) which would default to `1` but allow for `0` and then would be used as a bool (or some other way allowing to disable) to disable `docker compose pull` introduced in https://github.com/dandi/dandi-cli/pull/1121 to fix #1120 and which lead to dandi-archive integration testing not using freshly built docker image as discovered in https://github.com/dandi/dandi-archive/issues/1336#issuecomment-1286919392 .

### PR DESCRIPTION
**Pull request by jwodder**
Closes #1140.

### CODE REVIEW

**Review by yarikoptic — APPROVED** [review]
Thank you! Do we need a release to take advantage of this in dandi-archive testing? if so -- please add `release` label and merge

**Comment by yarikoptic** [comment]
answering my own question since was looking at that workflow anyways -- we do want release since we test against both dev and release, thus adding the label

**Comment by jwodder** [comment]
@yarikoptic Dandi Archive tests against both the latest release of dandi-cli and against the master branch, so a release isn't really needed.

**Comment by yarikoptic** [comment]
;-) indeed the fact that we test against both could be treated the other way as well (that no release is needed).  But I think we better re-establish the common base now, so I will keep the `release` label and can be merged as ubuntu CI runs complete

**Comment by yarikoptic** [comment]
hm, testing is failing but likely due to the dandi-archive introducing breaking change and this PR trying to allow to avoid that in the future. I do not see how this could add breakage, so will merge

**Pull request merged**
