### PR TITLE
RF: use callback mechanism of pyout to process files in parallel

### PR DESCRIPTION
**Pull request by yarikoptic**
unfortunately it stalls for unknown reason with first file record never populated

    $> dandi ls /home/yoh/proj/dandi/nwb-datasets/najafi-2018-nwb/data/FN_dataSharing/nwb/mouse1_fni16_15081{7,8}*nwb
    PATH                                                          SIZE     EXPERIMENTER    SESSION_ID   SESSION_START_TIME   KEYWORDS
    ...use1_fni16_150817_001_ch2-PnevPanResults-170808-190057.nwb 302.9 MB
    ...use1_fni16_150818_001_ch2-PnevPanResults-170808-180842.nwb 227.7 MB Farzaneh Najafi 170808180842 2015-08-17/20:00:00

that sample dataset could be obtained from

   https://github.com/dandi/najafi-2018-nwb

with nwb data hosted on

   http://datasets.datalad.org/?dir=/labs/churchland/najafi-2018-nwb

and linked to that github repo as autoenabled special remote.

### CODE REVIEW

**Comment by kyleam** [comment]
I'm having trouble getting into a state where I can debug this.  I have the dataset, with the two files in your example present locally:

```
$ git annex find                        
data/FN_dataSharing/nwb/mouse1_fni16_150817_001_ch2-PnevPanResults-170808-190057.nwb
data/FN_dataSharing/nwb/mouse1_fni16_150818_001_ch2-PnevPanResults-170808-180842.nwb
```

Before trying to debug anything on pyout's end, I wanted to make sure things were otherwise working for me.  I set `callback=False` and avoided swallowing exceptions:

<details>
<summary>patch</summary>

```diff
diff --git a/dandi/cli/command.py b/dandi/cli/command.py
index 8f46da1..639d3aa 100644
--- a/dandi/cli/command.py
+++ b/dandi/cli/command.py
@@ -54,7 +54,7 @@ def get_files(paths, recursive=True, recurion_limit=None):
     return paths
 
 
-def get_metadata_pyout(path, callback=True):
+def get_metadata_pyout(path, callback=False):
     """Return a metadata record for pyout
 
     Parameters
@@ -79,6 +79,7 @@ def _get_metadata_callback():
                 if v:
                     rec[f] = v
         except Exception as exc:
+            raise
             # lgr.error('Failed to get metadata from %s: %s', f, exc)
             pass
         return rec
```

</details>

When I run ` dandi ls data/FN_dataSharing/nwb/mouse1_fni16_15081{7,8}*nwb`, I see the following error:

<details>
<summary>get_metadata failure</summary>

```
Traceback (most recent call last):
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/build/map.py", line 1207, in construct
    obj.__init__(**kwargs)
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/pynwb/core.py", line 401, in __init__
    call_docval_func(super(VectorData, self).__init__, kwargs)
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/utils.py", line 327, in call_docval_func
    return func(*fargs, **fkwargs)
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/pynwb/core.py", line 335, in __init__
    call_docval_func(super(NWBData, self).__init__, kwargs)
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/utils.py", line 327, in call_docval_func
    return func(*fargs, **fkwargs)
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/pynwb/core.py", line 82, in __init__
    call_docval_func(super(NWBBaseType, self).__init__, kwargs)
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/utils.py", line 327, in call_docval_func
    return func(*fargs, **fkwargs)
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/utils.py", line 436, in func_call
    raise_from(ExceptionType(msg), None)
  File "<string>", line 3, in raise_from
TypeError: None is not allowed for 'data' (expected 'ndarray, list, tuple, Dataset, HDMFDataset or data', not None)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kyle/src/python/venvs/dandi-cli/bin/dandi", line 11, in <module>
    load_entry_point('dandi', 'console_scripts', 'dandi')()
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/kyle/src/python/dandi-cli/dandi/cli/command.py", line 189, in ls
    rec.update(get_metadata_pyout(path))
  File "/home/kyle/src/python/dandi-cli/dandi/cli/command.py", line 91, in get_metadata_pyout
    rec.update(_get_metadata_callback())
  File "/home/kyle/src/python/dandi-cli/dandi/cli/command.py", line 74, in _get_metadata_callback
    meta = get_metadata(path)
  File "/home/kyle/src/python/dandi-cli/dandi/pynwb_utils.py", line 30, in get_metadata
    nwb = io.read()
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/backends/hdf5/h5tools.py", line 293, in read
    return call_docval_func(super(HDF5IO, self).read, kwargs)
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/utils.py", line 327, in call_docval_func
    return func(*fargs, **fkwargs)
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/backends/io.py", line 35, in read
    container = self.__manager.construct(f_builder)
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/build/map.py", line 208, in construct
    result = self.__type_map.construct(builder, self, None)
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/build/map.py", line 1712, in construct
    return attr_map.construct(builder, build_manager, parent)
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/build/map.py", line 1175, in construct
    subspecs = self.__get_subspec_values(builder, self.spec, manager)
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/build/map.py", line 1117, in __get_subspec_values
    self.__get_sub_builders(groups, spec.groups, manager, ret)
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/build/map.py", line 1155, in __get_sub_builders
    ret.update(self.__get_subspec_values(sub_builder, subspec, manager))
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/build/map.py", line 1117, in __get_subspec_values
    self.__get_sub_builders(groups, spec.groups, manager, ret)
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/build/map.py", line 1147, in __get_sub_builders
    sub_builder = self.__flatten(sub_builder, subspec, manager)
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/build/map.py", line 1160, in __flatten
    tmp = [manager.construct(b) for b in sub_builder]
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/build/map.py", line 1160, in <listcomp>
    tmp = [manager.construct(b) for b in sub_builder]
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/build/map.py", line 204, in construct
    result = self.__type_map.construct(builder, self, parent)
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/build/map.py", line 1712, in construct
    return attr_map.construct(builder, build_manager, parent)
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/build/map.py", line 1175, in construct
    subspecs = self.__get_subspec_values(builder, self.spec, manager)
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/build/map.py", line 1117, in __get_subspec_values
    self.__get_sub_builders(groups, spec.groups, manager, ret)
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/build/map.py", line 1147, in __get_sub_builders
    sub_builder = self.__flatten(sub_builder, subspec, manager)
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/build/map.py", line 1160, in __flatten
    tmp = [manager.construct(b) for b in sub_builder]
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/build/map.py", line 1160, in <listcomp>
    tmp = [manager.construct(b) for b in sub_builder]
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/build/map.py", line 204, in construct
    result = self.__type_map.construct(builder, self, parent)
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/build/map.py", line 1712, in construct
    return attr_map.construct(builder, build_manager, parent)
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/build/map.py", line 1175, in construct
    subspecs = self.__get_subspec_values(builder, self.spec, manager)
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/build/map.py", line 1117, in __get_subspec_values
    self.__get_sub_builders(groups, spec.groups, manager, ret)
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/build/map.py", line 1147, in __get_sub_builders
    sub_builder = self.__flatten(sub_builder, subspec, manager)
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/build/map.py", line 1160, in __flatten
    tmp = [manager.construct(b) for b in sub_builder]
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/build/map.py", line 1160, in <listcomp>
    tmp = [manager.construct(b) for b in sub_builder]
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/build/map.py", line 204, in construct
    result = self.__type_map.construct(builder, self, parent)
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/build/map.py", line 1712, in construct
    return attr_map.construct(builder, build_manager, parent)
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/build/map.py", line 1175, in construct
    subspecs = self.__get_subspec_values(builder, self.spec, manager)
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/build/map.py", line 1118, in __get_subspec_values
    self.__get_sub_builders(datasets, spec.datasets, manager, ret)
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/build/map.py", line 1157, in __get_sub_builders
    ret[subspec] = manager.construct(sub_builder)
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/build/map.py", line 204, in construct
    result = self.__type_map.construct(builder, self, parent)
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/build/map.py", line 1712, in construct
    return attr_map.construct(builder, build_manager, parent)
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/home/kyle/src/python/venvs/dandi-cli/lib/python3.7/site-packages/hdmf/build/map.py", line 1210, in construct
    raise_from(Exception(msg), ex)
  File "<string>", line 3, in raise_from
Exception: Could not construct VectorData object
```

</details>

Here's my hdmf and pynwb versions from that virtual environment:

```
$ pip freeze | grep -e '\(hdmf\|pynwb\)'                      
hdmf==1.3.2                                        
pynwb==1.0.3
```

Do I need to do something else to set up dandi-cli and its dependencies aside from `pip install -e <dandi repo>`?

**Comment by mgrauer** [comment]
Probably related to [this](https://github.com/NeurodataWithoutBorders/pynwb/issues/1074).

**Comment by yarikoptic** [comment]
eh, I thought we would avoid running into those issues by restricting in setup.py with:

    pynwb >= 1.0.3,!=1.1.0
    hdmf != 1.1.2



> $ pip freeze | grep -e '\(hdmf\|pynwb\)'                      
> hdmf==1.3.2                                        
> pynwb==1.0.3

and I did a fresh install just today and got:
```shell
(dev3) yoh@ip-172-31-33-190:~/dandi-cli$ pip freeze | grep -e '\(hdmf\|pynwb\)' 
hdmf==1.3.2
pynwb==1.1.1
```
may be we should raise minimal pynwb to be 1.1.1?  with my versions of the libraries seems to work:
```shell
(dev3) yoh@ip-172-31-33-190:~/dandi-cli$ dandi ls ~ubuntu/najafi-2018-nwb/data/FN_dataSharing/nwb/mouse1_fni16_150817_001_ch2-PnevPanResults-170808-190057.nwb
PATH                                                          SIZE     EXPERIMENTER    SESSION_ID   SESSION_START_TIME   KEYWORDS
...use1_fni16_150817_001_ch2-PnevPanResults-170808-190057.nwb 302.9 MB Farzaneh Najafi 170808190057 2015-08-16/20:00:00          
Summary:                                                      302.9 MB                              2015-08-16/20:00:00>         
                                                                                                    2015-08-16/20:00:00<
```
downgrade to 1.0.3 indeed produces no details (sorry I have swallowed that exception in a rush without any log msg), so must be the culprit.  Please upgrade to pynwb==1.1.1

**Comment by kyleam** [comment]
> > $ pip freeze | grep -e '(hdmf|pynwb)'
> > hdmf==1.3.2
> > pynwb==1.0.3
> 
> and I did a fresh install just today and got:
> 
> ```shell
> (dev3) yoh@ip-172-31-33-190:~/dandi-cli$ pip freeze | grep -e '\(hdmf\|pynwb\)' 
> hdmf==1.3.2
> pynwb==1.1.1
> ```

Yes, I did a fresh install today too, but unfortunately it was before pynwb 1.1.1 was uploaded to pypi around 3 hours ago.  Upgrading resolves the failure I showed above.

**Comment by yarikoptic** [comment]
superseded by #17

**Pull request closed without merging**
